✨ Validate win
LouisaStrunk02/4Gewinnt pull request #3
Opened 2022-11-08 07:01 UTC by LouisaStrunk02

Changes:

- checks for win
- asks for playing again

2022-11-08 08:14 UTC, DevBastiS approved these changes

2022-11-08 08:14 UTC, DevBastiS commented on MainGame.py
> +        if self.turn_number > 42:
42 is a "magic number". Please move it to a constant and give it a speaking name.

2022-11-10 11:49 UTC, stefanluth requested changes

2022-11-10 11:49 UTC, stefanluth commented on MainGame.py
> +from asyncio import constants
This import is wrong :) asyncio is for handling asynchronous tasks.

2022-11-10 11:49 UTC, stefanluth commented on MainGame.py
> +    def round(self) -> None or Player:
`None or Player` is not a valid type :) Use [Optional](https://docs.python.org/3/library/typing.html#typing.Optional) or [Unions](https://docs.python.org/3/library/typing.html#typing.Union) instead

2022-11-10 11:49 UTC, stefanluth commented on StatusValidator.py
> +    def is_win(board: Board, player: Player) -> bool:
The first parameter should be `self`

2022-11-14 09:45 UTC, MKrips approved these changes

2022-11-14 12:47 UTC, stefanluth requested changes

2022-11-14 13:24 UTC, stefanluth requested changes

2022-11-14 13:24 UTC, stefanluth commented on StatusValidator.py
> +        is_diagonal_win = StatusValidator.diagonal_win(board, player)
```suggestion
        is_horizontal_win = self.horizontal_win(board,player)
        is_vertical_win = self.vertical_win(board, player)
        is_diagonal_win = self.diagonal_win(board, player)
```

2022-11-14 13:24 UTC, stefanluth commented on StatusValidator.py
> +        is_diagonal_win = StatusValidator.diagonal_win(board, player)
Other occurrences as well

2022-11-14 13:24 UTC, stefanluth commented on MainGame.py
> +                player_is_winner = StatusValidator.is_win(self.board, player)
This won't work because `StatusValidator` is not an instance of `StatusValidator`, which means the `self` parameter is missing :)

2022-11-14 13:52 UTC, stefanluth commented on MainGame.py
> +        ANZAHL_FELDER = 42
Place constants at the beginning of the file.

2022-11-14 13:53 UTC, LouisaStrunk02 commented on MainGame.py
> +                player_is_winner = StatusValidator.is_win(self.board, player)
Do I need this when using static methods?

2022-11-14 13:56 UTC, stefanluth commented on MainGame.py
> +                player_is_winner = StatusValidator.is_win(self.board, player)
No :D

2022-11-16 07:25 UTC, merged